# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='dob',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='testing',
            name='mobile',
            field=models.IntegerField(default=123),
        ),
    ]
