# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0002_auto_20170703_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dob', models.CharField(default='none', max_length=10)),
                ('mobile', models.IntegerField(default=123)),
            ],
        ),
        migrations.DeleteModel(
            name='testing',
        ),
    ]
