# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0003_auto_20170707_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='cattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('horn_size', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='cattle',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencv.user'),
        ),
    ]
