# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0004_auto_20170707_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='breed',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
