# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0006_auto_20170707_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
