# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0007_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
