# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0009_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='cattle',
            name='cattle_status',
            field=models.CharField(default='Alive', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='total_no_approved_claims',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_no_claims',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_no_false_claim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opencv.user'),
        ),
    ]
