# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0010_auto_20170710_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_register_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
