# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0011_auto_20170710_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='cattle_reg_appliction_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('horn_size', models.CharField(max_length=20)),
                ('cattle_status', models.CharField(default='Alive', max_length=10)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencv.user')),
            ],
        ),
    ]
