# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0013_auto_20170719_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='fid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='opencv.cattle_face'),
        ),
    ]
