# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0014_auto_20170719_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle_face',
            name='fid',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
