# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0022_cattle_f'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cattle_f',
            new_name='cattle_face_data',
        ),
        migrations.RemoveField(
            model_name='cattle_face',
            name='uid',
        ),
        migrations.AddField(
            model_name='cattle',
            name='fid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='opencv.cattle_face_data'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='cattle_face',
        ),
    ]
