# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0027_auto_20170719_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='fid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='opencv.cattle_fa'),
        ),
    ]
