# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0029_auto_20170719_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle_reg_appliction_req',
            name='cid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
