# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0030_cattle_reg_appliction_req_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register_request',
            name='aadhar',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='user_register_request',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
