# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0031_auto_20171013_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register_request',
            name='password',
            field=models.CharField(default='', max_length=225),
        ),
    ]
