# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0033_auto_20171017_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattle_reg_appliction_req',
            name='uid',
        ),
    ]
